events/urls.py
from django.urls import path

from . import views

app_name = "event"
urlpatterns = [
    path("", views.index, name="index"),
    path("create/", views.create, name="create"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("polls/", include("polls.urls")),
    path("events/", include("events.urls")),
    path("todo/", include("todo.urls")),
    path("todo2/", include("todo.urls")),
    path("admin/", admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

app_name = "polls"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

todo/urls.py
from django.urls import path

from . import views

app_name = "todo"
urlpatterns = [
    path("list/", views.list, name="list"),
    path("edit/", views.edit, name="edit"),
    # path("edit/<int:todo_id>/update", views.update, name="update"),
    # path("create/", views.create, name="create"),
    path("delete/<int:todo_id>", views.delete, name="delete"),
    path("list2/", views.list2, name="list2"),
    path("edit2/", views.edit2, name="edit2"),
]

events/models.py
from django.db import models


class Event(models.Model):
    events_title = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return f"{self.pk} ({self.events_title})"

polls/models.py
import datetime
from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

todo/models.py
from django.db import models


class Todo(models.Model):
    todo_title = models.CharField(max_length=100)

events/views.py
# from django.http import HttpResponse

from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse

from events import models


def create(request):
    title = request.POST.get("title")
    new_event = models.Event()
    new_event.events_title = title
    new_event.save()
    return HttpResponseRedirect(reverse("event:index"))


def index(request):
    all_event = models.Event.objects.all()
    context = {"all_event": all_event}
    return render(request, "events/main.html", context)

polls/views.py
from django.db.models import F
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic

from .models import Choice, Question

from django.utils import timezone


class IndexView(generic.ListView):
    template_name = "polls/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by(
            "-pub_date"
        )[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = "polls/detail.html"


class ResultsView(generic.DetailView):
    model = Question
    template_name = "polls/results.html"

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "polls/detail.html",
            {
                "question": question,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        selected_choice.votes = F("votes") + 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))

todo/views.py
from django.shortcuts import render
from django.http import HttpResponse

from todo import models


def list(request):
    # データの登録
    new_todo = models.Todo()
    new_todo.todo_title = title
    new_todo.save()
    # return HttpResponseRedirect(reverse("todo.list"))

    # 　データの取得
    all_todo = models.Todo.objects.all()
    context = {"todos": all_todo}
    return render(request, "index.html", context)


def edit(request,todo_id):
    return HttpResponse("edit")


def delete(request,todo_id):
    target_todo = models.Todo.objects.get(id=todo_id)


def list2(request):
    return HttpResponse("list2")


def edit2(request):
    return HttpResponse("edit2")

events/templates/events/main.html
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>調整</title>
</head>

<body>
    <h1>スケジュール調整アプリ</h1>
    <form action="{% url 'event:create' %}" method="post">
        {% csrf_token %}
        <input type="text" name="title">
        <input type="submit" name="登録">
    </form>

    {% for event in all_event %}
    {{ event.description }}
    {{ event.events_title }} <br>
    {% endfor %}
</body>

</html>

polls/templates/polls/detail.html
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <form action="{% url 'polls:vote' question.id %}" method="post">
        {% csrf_token %}
        <fieldset>
            <legend>
                <h1>{{ question.question_text }}</h1>
            </legend>
            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
            {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
            {% endfor %}
        </fieldset>
        <input type="submit" value="Vote">
    </form>
</body>

</html>

polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'polls/style.css' %}">
</head>

<body>
    {% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
        {% endfor %}
    </ul>
    {% else %}
    <p>No polls are available.</p>
    {% endif %}
</body>

</html>

polls/templates/polls/results.html
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h1>{{ question.question_text }}</h1>

    <ul>
        {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
        {% endfor %}
    </ul>

    <a href="{% url 'polls:detail' question.id %}">Vote again?</a>
</body>

</html>